src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CustomerRepository::class)]
class Customer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $mail = null;

    #[ORM\Column(length: 255)]
    private ?string $society_name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private \DateTime $date_add;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): static
    {
        $this->mail = $mail;

        return $this;
    }

    public function getSocietyName(): ?string
    {
        return $this->society_name;
    }

    public function setSocietyName(string $society_name): static
    {
        $this->society_name = $society_name;

        return $this;
    }

    public function getDateAdd(): ?\DateTime
    {
        return $this->date_add;
    }

    public function setDateAdd(\DateTime $date_add): static
    {
        $this->date_add = $date_add;

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\DBAL\Types\Types;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column(type: Types::TEXT)]
    private string $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function fromArray(array $data): self {
        $this->id = $data['id'] ?? null;
        $this->name = $data['name'];
        $this->description = $data['description'];
        $this->price = $data['price'];

        return $this;
    }
}

src/Controller/ContactController.php
<?php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class ContactController extends AbstractController
{
    #[Route('/contact', name: 'contact_index', methods: ['GET'])]
    public function list(): Response
    {
        return $this->render('contact/index.html.twig', []);
    }
}

src/Controller/CustomerController.php
<?php
namespace App\Controller;

use App\Repository\CustomerRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class CustomerController extends AbstractController
{
    #[Route('/customers', name: 'customer_list', defaults: ['page' => '1'], methods: ['GET'])]
    #[Route('/customers/{page}', name: 'customer_list_paginated', methods: ['GET'])]
    public function list(int $page, CustomerRepository $customers): Response
    {
        $customers = $customers->getAllCustomers($page);
        return $this->render('customer/list.html.twig', [
            'paginator' => $customers
        ]);
    }
}

src/Controller/HomeController.php
<?php
namespace App\Controller;

use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\File;

class HomeController extends AbstractController
{
    #[Route('/', name: 'home_index', methods: ['GET'])]
    public function index(): Response
    {
        return $this->render('home/index.html.twig', []);
    }

    #[Route('/download/{filename}', name: 'home_download', methods: ['GET'])]
    public function download(string $filename): BinaryFileResponse
    {
        return $this->file(new File($filename));
    }

    #[Route('/api/helloword/{name}', name: 'api_helloword')]
    public function apiHelloword(string $name): Response
    {
        return new JsonResponse('Hello ' . $name . ' !');
    }
}

src/Controller/ProductController.php
<?php
namespace App\Controller;

use App\Repository\ProductRepository;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class ProductController extends AbstractController
{
    #[Route('/products', name: 'product_list', methods: ['GET'])]
    public function list(): Response
    {
        return $this->render('product/list.html.twig');
    }

    #[Route('/api/product/listproducts', name: 'api_product_list', defaults: ['page' => '1'], methods: ['GET'])]
    #[Route('/api/product/listproducts/{page}', name: 'api_product_list_paginated', methods: ['GET'])]
    public function apiList(int $page, ProductRepository $products): JsonResponse
    {
        $paginator = $products->getAllPaginated($page);
        return $this->json($paginator);
    }
}

templates/Product/list.html.twig
{% extends 'base.html.twig' %}

{% block body_id 'product_list' %}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Test technique Coquille{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}" />
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body class="d-flex flex-column h-100">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <a class="navbar-brand" href="{{ path('home_index') }}">Test technique Coquille</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav">
                    <li class="nav-item {% if app.request.pathinfo == path('home_index') %} active {% endif %}">
                        <a class="nav-link" href="{{ path('home_index') }}">Accueil</a>
                    </li>
                    <li class="nav-item {% if app.request.pathinfo == path('customer_list') %} active {% endif %}">
                        <a class="nav-link" href="{{ path('customer_list') }}">Clients</a>
                    </li>
                    <li class="nav-item {% if app.request.pathinfo == path('product_list') %} active {% endif %}">
                        <a class="nav-link" href="{{ path('product_list') }}">Produits</a>
                    </li>
                    <li class="nav-item {% if app.request.pathinfo == path('contact_index') %} active {% endif %}">
                        <a class="nav-link" href="{{ path('contact_index') }}">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>

        <main role="main" class="flex-shrink-0">
            <div class="container" id="{% block body_id %}{% endblock %}">
                {% block body %}{% endblock %}
            </div>
        </main>

        <footer class="footer mt-auto bg-dark">
            <div class="container text-white text-center">
                 {{ component('FooterMessage') }}
            </div>
        </footer>
    </body>
</html>

templates/components/FooterMessage.html.twig
{{ message }}

templates/contact/index.html.twig
{% extends 'base.html.twig' %}

{% block body_id 'contact_index' %}

{% block body %}
<div class="card p-5">
        <div class="row">
            <div class="col-sm-6"> 
                    <h1 class="font-weight-bold">Contactez nous !</h1>
                    
                    <small class="form-text text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</small>
                    
                    <div class="cardContact" style="">

                        <div class="">
                            <div class="containerText">
                                <p><span class="validation">&#x2713;</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ullamcorper arcu id ante maximus vehicula. Aliquam at dui quis sem elementum lacinia pretium a nunc.</p>
                            </div>
                        </div>

                        <div class="containerSeparation">
                            <hr class="separationCard">
                        </div>

                        <div class="">
                            <div class="containerText">
                                <p><span class="validation">&#x2713;</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ullamcorper arcu id ante maximus vehicula. Aliquam at dui quis sem elementum lacinia pretium a nunc.</p>
                            </div>
                        </div>
                        
                         <div class="containerSeparation">
                            <hr class="separationCard">
                        </div>

                        <div class="">
                            <div class="containerText">
                                <p><span class="validation">&#x2713;</span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ullamcorper arcu id ante maximus vehicula. Aliquam at dui quis sem elementum lacinia pretium a nunc.</p>
                            </div>
                        </div>
                    </div>

                    <small class="form-text text-muted">Lorem ipssuuum <a href="#" class="link-primary">dima</a></small>


            </div>

            <div class="col-sm-6"> 
                <form>
                <div class="form-row">
                    <div class="form-group col-md-6">
                    <label>Prénom *</label>
                    <input type="email" class="form-control">
                    </div>
                    <div class="form-group col-md-6">
                    <label>Nom *</label>
                    <input type="password" class="form-control">
                    </div>
                </div>

                <div class="form-group">
                    <label>Email *</label>
                    <input type="text" class="form-control">
                </div>

                <div class="form-group">
                    <label>Société</label>
                    <input type="text" class="form-control">
                </div>

                <div class="form-group">
                    <label>Taille de votre société</label>
                    <select class="form-control">
                        <option value="" selected disabled hidden>Choisissez ...</option>
                        <option value="">Micro entreprise</option>
                        <option value="">Petite et moyenne entreprise</option>
                        <option value="">Entreprise de taille intermédiaire</option>
                        <option value="">Grande entreprise</option>
                    </select>
                </div>

                <div class="form-group">
                    <label>Message *</label>
                    <textarea type="text" style="max-height : 180px;" class="form-control"></textarea>
                </div>  

                <div class="form-group"> 
                    <small class="form-text text-muted">Les champs marqués d'un astérisque (*) sont obligatoires.</small>
                </div>
                
                <div class="form-group">
                    <button class="btn btn-primary">Envoyer</button>
                </div>
                </form>
            </div>
        </div>
        
        
{% endblock %}

templates/customer/list.html.twig
{% extends 'base.html.twig' %}


{% block body_id 'customer_list' %}

{% block body %}
    <div class="card mb-3">
        <div class="card-body text-center">
            <div class="mb-3">
                <h1>Liste des clients</h1>
                <p class="text-secondary">(Données réelles)</p>
            </div>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Prénom</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Mail</th>
                    <th scope="col">Société</th>
                    <th scope="col">Date d'inscription</th>
                </tr>
                </thead>
                <tbody>
                {% for customer in paginator.results %}
                    <tr>
                        <td>{{ customer.firstname }}</td>
                        <td>{{ customer.lastname }}</td>
                        <td>{{ customer.mail }}</td>
                        <td>{{ customer.societyName }}</td>
                        <td>{{ customer.dateAdd|date('d-m-Y H:i') }}</td>
                    </tr>
                {% endfor %}
                </tbody>
                {{ dump(paginator.results) }}
            </table>

            {% if paginator.hasToPaginate %}
                <nav class="row justify-content-md-center">
                    <ul class="pagination">
                        <li class="page-item {% if paginator.hasPreviousPage == false %}disabled{% endif %}">
                            <a class="page-link" href="{{ path('customer_list_paginated', {page: paginator.previousPage}) }}" tabindex="-1">Previous</a>
                        </li>

                        {% for i in 1..paginator.lastPage %}
                            {% if i == paginator.currentPage %}
                                <li class="page-item active">
                                  <span class="page-link">
                                    {{ i }}
                                    <span class="sr-only">(current)</span>
                                  </span>
                                </li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="{{ path('customer_list_paginated', {page: i}) }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}

                        <li class="page-item {% if paginator.hasNextPage == false %}disabled{% endif %}">
                            <a class="page-link" href="{{ path('customer_list_paginated', {page: paginator.nextPage}) }}">Next</a>
                        </li>
                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block body_id 'home_index' %}

{% block body %}
    <div class="card">
        <div class="card-body p-5">
            <h1 class="text-center">Bienvenue sur le test technique de Coquille !</h1>
            <div class="mt-5 text-left">
                <p>
                    Le but de ce test est de mieux connaître tes compétences, ce n'est pas un examen d'entrée chez Coquille.
                    Nous serons plus attentifs à ta manière de coder et de résoudre les problèmes plutôt qu'au résultat final.
                </p>
                <p>
                    Le test dure environ <strong>2 heures</strong>, essaye de ne pas y passer plus de temps.
                    Ce n'est pas grave si tout n'est pas terminé.
                </p>
                <p>
                    Concentre-toi d'abord sur <strong>les 2 premiers exercices</strong> qui sont assez simples.
                    Ensuite, si tu manques de temps, tu peux choisir entre <strong>l'exercice 3</strong> si tu as un profil plutôt Front-end ou <strong>l'exercice 4</strong> si tu as un profil plutôt Back-end.
                </p>
            </div>
            <div class="mt-5 text-center">
                N'hésite pas à me contacter si tu as des questions ou si tu restes bloqué trop longtemps sur un exercice.
            </div>
            <div class="mt-3 text-center">
                <h4>Bonne chance !</h4>
            </div>
            <hr>
            <div class="text-left">
                <ul>
                    <li class="my-4">
                        <strong>1.</strong> Sur la page des clients, un problème de pagination empêche le changement de
                        page. Peux-tu le corriger, s'il te plaît ?
                    </li>
                    <li class="my-4">
                        <strong>2.</strong> Il faudrait ajouter la colonne "Société" dans le tableau des clients (le champ est déjà
                        présent dans la BDD et le model, il faut seulement l'afficher)
                    </li>
                    <li class="my-4">
                        <strong>3.</strong> Intégrer le mock up <a
                            href="{{ path("home_download", {filename: "mock-up_contact_page.png"}) }}">suivant</a> sur
                        la page "Contact". Tu peux utiliser <strong>symfony run watch</strong> pour que ton scss se compile
                        automatiquement.
                        N'hésite pas à améliorer le style si tu en as envie.
                    </li>
                    <li class="my-4">
                        <strong>4.</strong> Terminer le CRUD (Create, Read, Update, Delete) pour la page produit. Le but est de faire fonctionner les boutons d'ajout, de modification et de suppression.
                        Tout le code de la vue Produits est dans le fichier <strong>assets/js/vue/Product.vue</strong> pour simplifier un peu l'exercice.
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}